CREATE TABLE IF NOT EXISTS {}.blog_posts (
    id INT(12) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    author_id INT(12) NOT NULL,
    title VARCHAR(100) NOT NULL,
    text MEDIUMTEXT NOT NULL,
    keyword1 VARCHAR(30) NOT NULL,
    keyword2 VARCHAR(30) NOT NULL,
    image VARCHAR(400) NOT NULL,
    bg_src VARCHAR(400) NOT NULL,
    bg_type VARCHAR(30) NOT NULL,
    active TINYINT(1) NOT NULL DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON CREATE CURRENT_TIMESTAMP,

    INDEX bpauthor_id (author_id),

    CONSTRAINT fk_author_id FOREIGN KEY (author_id) REFERENCES users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);