CREATE TABLE IF NOT EXISTS {}.users (
    id INT(12) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    role_id INT(12) NOT NULL,
    username VARCHAR(30) NOT NULL,
    email VARCHAR(50) NOT NULL,
    image VARCHAR(255) NOT NULL,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON CREATE CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    INDEX ueamil (email),

    CONSTRAINT fk_role_id FOREIGN KEY (role_id) REFERENCES roles(id),
    ON DELETE CASCADE,
    ON UPDATE CASCADE
);